### PR TITLE
Add get_node_properties function

### PR DESCRIPTION
**Pull request by eyasubirhanu**

### CODE REVIEW

**Comment by Habush** [comment]
@tanksha are you reviewing the PRs before merging them? 

The `__pycache__` and `biocypher_logs` directories should not be committed to the repo and should be added to `.gitignore`.

**Comment by eyasubirhanu** [comment]
Hey Abdulrahman, I've already fixed it in the new PR and added them to the
.gitignore.

**Comment by tanksha** [comment]
They have been deleted in this PR but @eyasubirhanu there are [pycache](https://github.com/rejuve-bio/annotation-query-backend/tree/main/gene_annotaion/__pycache__) files from previous, please remove them and send a new PR

**Comment by eyasubirhanu** [comment]
Ok, will do that.

**Comment by Habush** [comment]
@eyasubirhanu Please assign @tanksha and me in future PRs as reviewers. Then, either of us, depending on our other priorities and availability, will review your PRs. This helps us keep up with your work and catch minor issues like the above that you might miss. Also, thanks @tanksha for taking care of the PRs so far!

**Comment by eyasubirhanu** [comment]
Sure thing, will do! thanks for the heads-up and support.

**Comment by eyasubirhanu** [comment]
hey abdulrahman and @tanksha, It appears that I don't have the necessary
permissions to add reviewers to the PR

**Pull request merged**
